### ISSUE TITLE
How to use Animation and materialise UI Using cordova as android for Hybrid app

### ISSUE THREAD

**Issue by devopsexpro** [apache/cordova-contribute#30]
Hi Everyone,

I have developed Hybrid App using Cordova apache for Android .in that I have used PHP in backend and frontend is html5 CSS, javascript, my app is work in android. but when I use animation or materialize frontend Template.it is not working in a hybrid app using Cordova as android ..Why?? please brief and Inform how do I implement it..Kindly Inform

**Comment by timbru31** [comment]
You already created https://github.com/apache/cordova/issues/125 - one issue is more than enough.
